items_de = {
    "Gold Bar 1,000G": "Goldbarren 1.000G",
    "Bartali Sailboat": "Bartali-Segelboot",
    "Epheria Sailboat": "Epheria-Segelboot",
    "Epheria Frigate": "Epheria-Fregatte",
    "Epheria Caravel": "Epheria-Karavelle",
    "Epheria Galleass": "Epheria-Galeasse",
    "Ship Upgrade Permit: Epheria Sailboat": "Schiffsupgrade-Erlaubnis: Epheria-Segelboot",
    "Ship Upgrade Permit: Epheria Frigate": "Schiffsupgrade-Erlaubnis: Epheria-Fregatte",
    "Ship Upgrade Permit: Epheria Caravel": "Schiffsupgrade-Erlaubnis: Epheria-Karavelle",
    "Ship Upgrade Permit: Epheria Galleass": "Schiffsupgrade-Erlaubnis: Epheria-Galeasse",
    "Ultimate Armor Reform Stone": "Ultimativer Rüstungs-Reformstein",
    "Ultimate Weapon Reform Stone": "Ultimativer Waffen-Reformstein",
    "Black Stone": "Schwarzer Stein",
    "Bartali Sailboat: Old Prow": "Bartali-Segelboot: Alter Bug",
    "Bartali Sailboat: Old Plating": "Bartali-Segelboot: Alte Panzerung",
    "Bartali Sailboat: Old Cannon": "Bartali-Segelboot: Alte Kanone",
    "Bartali Sailboat: Old Sail": "Bartali-Segelboot: Altes Segel",
    "Epheria: Old Figurehead": "Epheria: Alte Galionsfigur",
    "Epheria: Old Plating": "Epheria: Alte Panzerung",
    "Epheria: Old Cannon": "Epheria: Alte Kanone",
    "Epheria: Old Wind Sail": "Epheria: Altes Windsegel",
    "Epheria Caravel: Brass Prow": "Epheria-Karavelle: Messingbug",
    "Epheria Caravel: Upgraded Plating (Green)": "Epheria-Karavelle: Verbesserte Panzerung (Grün)",
    "Epheria Caravel: Verisha Cannon": "Epheria-Karavelle: Verisha-Kanone",
    "Epheria Caravel: White Wind Sail": "Epheria-Karavelle: Weißes Windsegel",
    "Epheria Galleass: White Horn Prow": "Epheria-Galeasse: Weißer Hornbug",
    "Epheria Galleass: Upgraded Plating (Green)": "Epheria-Galeasse: Verbesserte Panzerung (Grün)",
    "Epheria Galleass: Verisha Cannon": "Epheria-Galeasse: Verisha-Kanone",
    "Epheria Galleass: White Wind Sail": "Epheria-Galeasse: Weißes Windsegel",
    "Epheria Caravel: Black Dragon Prow": "Epheria-Karavelle: Schwarzer Drachenbug",
    "Epheria Caravel: Upgraded Plating (Blue)": "Epheria-Karavelle: Verbesserte Panzerung (Blau)",
    "Epheria Caravel: Mayna Cannon": "Epheria-Karavelle: Mayna-Kanone",
    "Epheria Caravel: Stratus Wind Sail": "Epheria-Karavelle: Stratus-Windsegel",
    "Epheria Galleass: Black Dragon Prow": "Epheria-Galeasse: Schwarzer Drachenbug",
    "Epheria Galleass: Upgraded Plating (Blue)": "Epheria-Galeasse: Verbesserte Panzerung (Blau)",
    "Epheria Galleass: Mayna Cannon": "Epheria-Galeasse: Mayna-Kanone",
    "Epheria Galleass: Stratus Wind Sail": "Epheria-Galeasse: Stratus-Windsegel",
    "Sea Monster's Ooze": "Schleim des Seeungeheuers",
    "Graphite Ingot for Upgrade": "Graphitbarren für Upgrade",
    "Timber for Upgrade": "Holz für Upgrade",
    "Adhesive for Upgrade": "Klebstoff für Upgrade",
    "Zinc Ingot": "Zinkbarren",
    "Old Tree Bark": "Alte Baumrinde",
    "Red Tree Lump": "Roter Baumklumpen",
    "White Cedar Sap": "Weißer Zedernsaft",
    "Acacia Sap": "Akaziensaft",
    "Elder Tree Sap": "Holunderbaumsaft",
    "Standardized Timber Square": "Standardisiertes Holzquadrat",
    "Steel": "Stahl",
    "Pine Plywood": "Kiefernsperrholz",
    "Flax Fabric": "Leinenstoff",
    "Hard Pillar": "Harter Pfeiler",
    "Jade Coral Ingot": "Jadekorallen-Barren",
    "Pine Coated Plywood": "Beschichtetes Kiefernsperrholz",
    "Enhanced Flax Fabric": "Verbesserter Leinenstoff",
    "Blueprint: Panokseon": "Bauplan: Panokseon",
    "Wooden Nail Soaked in Seawater": "In Meerwasser getränkter Holznagel",
    "Finely Polished Pine Plywood": "Fein poliertes Kiefernsperrholz",
    "Glue With Traces of Deep Waves": "Klebstoff mit Spuren tiefer Wellen",
    "Sangpyeong Coin": "Sangpyeong-Münze",
    "Khan's Concentrated Magic": "Khans konzentrierte Magie",
    "Luminous Cobalt Ingot": "Leuchtender Kobaltbarren",
    "Bright Reef Piece": "Helles Riffstück",
    "Great Ocean Dark Iron": "Dunkles Eisen des Großen Ozeans",
    "Cobalt Ingot": "Kobaltbarren",
    "Brilliant Rock Salt Ingot": "Brillanter Steinsalzbarren",
    "Seaweed Stalk": "Seetangstängel",
    "Enhanced Island Tree Coated Plywood": "Verbessertes beschichtetes Inselbaum-Sperrholz",
    "Pure Pearl Crystal": "Reiner Perlenkristall",
    "Cox Pirates' Artifact (Parley Beginner)": "Cox-Piraten-Artefakt (Verhandlung Anfänger)",
    "Cox Pirates' Artifact (Parley Expert)": "Cox-Piraten-Artefakt (Verhandlung Experte)",
    "Cox Pirates' Artifact (Combat)": "Cox-Piraten-Artefakt (Kampf)",
    "Deep Sea Memory Filled Glue": "Mit Tiefseeerinnerungen gefüllter Klebstoff",
    "Brilliant Pearl Shard": "Brillante Perlenscherbe",
    "Ruddy Manganese Nodule": "Rötlicher Manganknollen",
    "Tear of the Ocean": "Träne des Ozeans",
    "Khan's Tendon": "Khans Sehne",
    "Khan's Scale": "Khans Schuppe",
    "Tide-Dyed Standardized Timber Square": "Gezeitengefärbtes standardisiertes Holzquadrat",
    "Deep Tide-Dyed Standardized Timber Square": "Tief gezeitengefärbtes standardisiertes Holzquadrat",
    "Moon Vein Flax Fabric": "Mondader-Leinenstoff",
    "Moon Scale Plywood": "Mondschuppen-Sperrholz",
    "Tidal Black Stone": "Gezeiten-Schwarzstein",
    "Mandragora Essence": "Alraunen-Essenz"
}