barters_de = {
    "Bright Reef Piece": "Helles Riffstück",
    "Brilliant Pearl Shard": "Brillante Perlenscherbe",
    "Brilliant Rock Salt Ingot": "Brillanter Steinsalzbarren",
    "Cobalt Ingot": "Kobaltbarren",
    "Cox Pirates' Artifact (Parley Beginner)": "Cox-Piraten-Artefakt (Verhandlung Anfänger)",
    "Cox Pirates' Artifact (Parley Expert)": "Cox-Piraten-Artefakt (Verhandlung Experte)",
    "Cox Pirates' Artifact (Combat)": "Cox-Piraten-Artefakt (Kampf)",
    "Deep Sea Memory Filled Glue": "Mit Tiefseeerinnerungen gefüllter Klebstoff",
    "Enhanced Island Tree Coated Plywood": "Verbessertes beschichtetes Inselbaum-Sperrholz",
    "Great Ocean Dark Iron": "Dunkles Eisen des Großen Ozeans",
    "Island Tree Coated Plywood": "Beschichtetes Inselbaum-Sperrholz",
    "Luminous Cobalt Ingot": "Leuchtender Kobaltbarren",
    "Moon Scale Plywood": "Mondschuppen-Sperrholz",
    "Moon Vein Flax Fabric": "Mondader-Leinenstoff",
    "Pure Pearl Crystal": "Reiner Perlenkristall",
    "Rock Salt Ingot": "Steinsalzbarren",
    "Ruddy Manganese Nodule": "Rötlicher Manganknollen",
    "Seaweed Stalk": "Seetangstängel",
    "Tear of the Ocean": "Träne des Ozeans",
    "Tidal Black Stone": "Gezeiten-Schwarzstein",
    "Tide-Dyed Standardized Timber Square": "Gezeitengefärbtes standardisiertes Holzquadrat",
    "Deep Tide-Dyed Standardized Timber Square": "Tief gezeitengefärbtes standardisiertes Holzquadrat",
    "any level 2 barter good": "beliebiger Bartergegenstand der Stufe 2",
    "any level 3 barter good": "beliebiger Bartergegenstand der Stufe 3",
    "[Level 3] Pirates' Supply Box": "[Stufe 3] Piraten-Vorratskiste",
    "[Level 3] Weasel Leather Coat": "[Stufe 3] Wiesel-Ledermantel",
    "[Level 3] Lopters Fishnet": "[Stufe 3] Lopters Fischernetz",
    "[Level 5] Azure Quartz": "[Stufe 5] Azurquarz",
    "[Level 5] Elixir of Youth": "[Stufe 5] Elixier der Jugend",
    "[Level 5] Mysterious Rock": "[Stufe 5] Mysteriöser Stein",
    "[Level 5] Golden Fish Scale": "[Stufe 5] Goldene Fischschuppe",
    "[Level 5] Faded Gold Dragon Figurine": "[Stufe 5] Verblasste goldene Drachenfigur",
    "[Level 5] Portrait of the Ancient": "[Stufe 5] Porträt der Alten",
    "[Level 5] Luxury Patterned Fabric": "[Stufe 5] Luxuriöser gemusterter Stoff",
    "[Level 5] 102 Year Old Golden Herb": "[Stufe 5] 102 Jahre altes goldenes Kraut",
    "[Level 5] Taxidermied White Caterpillar": "[Stufe 5] Präparierte weiße Raupe",
    "[Level 2] Pirate Ship Mast": "[Stufe 2] Piratenschiff-Mast",
    "[Level 2] Supreme Oyster Box": "[Stufe 2] Erstklassige Austernbox",
    "[Level 2] Sea Survival Kit": "[Stufe 2] Überlebensset für die See",
    "[Level 2] Opulent Marble": "[Stufe 2] Opulenter Marmor",
    "[Level 2] Big Stone Slab": "[Stufe 2] Große Steinplatte",
    "[Level 2] Monster Tentacle": "[Stufe 2] Monster-Tentakel",
    "[Level 4] Amethyst Fragment": "[Stufe 4] Amethyst-Fragment",
    "[Level 4] Headless Dragon Figurine": "[Stufe 4] Kopflose Drachenfigur",
    "[Level 3] Torn Pirate Treasure Map": "[Stufe 3] Zerrissene Piraten-Schatzkarte",
    "[Level 3] Gooey Monster Blood": "[Stufe 3] Klebriges Monsterblut",
    "[Level 3] Rare Herb Pile": "[Stufe 3] Seltener Kräuterhaufen",
    "[Level 3] Blue Candle Bundle": "[Stufe 3] Blaues Kerzenbündel",
    "[Level 4] Marine Knights' Spear": "[Stufe 4] Speer der Meeresritter",
    "[Level 4] Bronze Candlestick": "[Stufe 4] Bronzener Kerzenhalter",
    "[Level 4] Stolen Pirate Dagger": "[Stufe 4] Gestohlener Piratendolch",
    "[Level 4] Opulent Thread Spool": "[Stufe 4] Opulente Garnspule",
    "[Level 4] Green Salt Lump": "[Stufe 4] Grüner Salzklumpen",
    "[Level 4] Panacea": "[Stufe 4] Allheilmittel",
    "[Level 4] Pirate's Key": "[Stufe 4] Piratenschlüssel",
    "[Level 4] Solidified Lava": "[Stufe 4] Erstarrte Lava",
    "[Level 4] Old Chest with Gold Coins": "[Stufe 4] Alte Truhe mit Goldmünzen",
    "[Level 4] Seashell Deco": "[Stufe 4] Muschel-Deko",
    "[Level 5] Octagonal Box": "[Stufe 5] Achteckige Box",
    "[Level 5] Statue's Tear": "[Stufe 5] Träne der Statue",
    "[Level 5] Supreme Gold Candlestick": "[Stufe 5] Erstklassiger goldener Kerzenhalter",
    "[Level 5] Taxidermied Morpho Butterfly": "[Stufe 5] Präparierter Morpho-Schmetterling",
}